<<script>
export default {
    
}
//make for loop making componennt foreacht crypto there is
</script>
    <template>
        <div class="crypto-container">
            <tr>ranking number </tr>
            <tr>name </tr>
            <tr> price </tr>
            <tr>24% </tr>
            <tr>7d% </tr>
            <tr>market cap </tr>
            <tr>volume(24h) </tr>
            <tr>circulating supply </tr>

        </div>
    </template>
<style scoped>

</style>